### ISSUE TITLE
Almost there...

### ISSUE THREAD

**Issue by i-am-the-slime** [hendrikniemann/purescript-graphql-fullstack-example#1]
It fails for me with this error:
```
{
  "data": {
    "createTodo": null
  },
  "errors": [
    {
      "message": "SQLITE_ERROR: no such table: todo",
      "path": [
        "createTodo"
      ]
    }
  ]
}
```

But sqlite3 tells me that the table exists:
```
Error: table "todo" already exists
```
What else could I be trying?

**Comment by hendrikniemann** [comment]
Maybe you are not passing in the location to the database correctly?

I have my database in a `/data/` folder next to the `/backend/` folder. My `.env` file looks like this:

```
DATABASE_URI=../data/todos.sqlite
JWT_SECRET=example-secret
```

And then finally I start the server with `npm run dev`.
